"""Phase 3 — export the interactive VBI explorer (realistic 40 m, damped).

Runs the quarter-car across the realistic 40 m overpass (Rayleigh ζ=2%) at a grid
of speeds. For each speed it records the animation frames, the mid-span history,
the DAF, and the B-WIM recovered weight. The web page (web/explore.html) then
lets you slide the speed and watch the deflection, the DAF, and the DAF-vs-speed
curve update live.

    python solver/export_explore.py   ->  output/explore_data.js
"""

from __future__ import annotations

import json
import os

import numpy as np

from beam_fem import Beam, free_dofs, natural_frequencies
from vehicle import QuarterCar, integrate_coupled
from bwim import moses_recover

# realistic 40 m overpass (matches verify_p1) + damping
L, E, I, M_BAR = 40.0, 2.1e11, 0.40, 12000.0
ZETA = 0.02
CAR = QuarterCar(m_s=9000.0, m_u=1000.0, k_s=2.0e6, k_t=1.0e7, c_s=6.0e4)
X_GAUGE = L / 2.0
SPEEDS = [10, 15, 20, 30, 45, 60, 80, 110]   # m/s
N_FRAMES = 100
N_SERIES = 400


def main():
    beam = Beam(L=L, E=E, I=I, mass_per_length=M_BAR, n_elements=20)
    f1 = float(natural_frequencies(beam, 1)[0])
    free_idx = free_dofs(beam)
    node_x = np.array([beam.node_x(k) for k in range(beam.n_nodes)])
    z_s0, z_u0 = CAR.static_equilibrium()
    W = CAR.weight
    static_mid = W * L**3 / (48 * E * I)

    scenarios, max_w = [], 0.0
    for v in SPEEDS:
        probe = integrate_coupled(beam, CAR, v, damping_ratio=ZETA,
                                  moment_section=X_GAUGE)
        stride = max(1, (len(probe.t) - 1) // N_FRAMES)
        res = integrate_coupled(beam, CAR, v, damping_ratio=ZETA,
                                moment_section=X_GAUGE, frame_stride=stride)
        # B-WIM recovered weight
        Wr, _ = moses_recover(beam, X_GAUGE, v * res.t, res.moment, axle_offsets=(0.0,))
        Wr = float(Wr[0])

        frames = []
        u_full = np.zeros(beam.n_dof)
        for i in range(len(res.frames_t)):
            u_full[:] = 0.0
            u_full[free_idx] = res.frames_u[i]
            node_w = u_full[0::2].copy()
            max_w = max(max_w, float(np.max(np.abs(node_w))))
            xv = min(v * res.frames_t[i], L)
            frames.append({"t": res.frames_t[i], "w": node_w, "xv": xv,
                           "wc": float(np.interp(xv, node_x, node_w)),
                           "body": res.frames_zs[i] - z_s0,
                           "fc": res.frames_fc[i]})

        s = max(1, (len(res.t) - 1) // N_SERIES)
        scenarios.append({
            "speed": v, "daf": res.daf, "w_rec": Wr,
            "peak_mid_mm": float(np.max(np.abs(res.w_mid)) * 1e3),
            "frames": frames,
            "series_t": res.t[::s], "series_wmid": res.w_mid[::s],
        })
        print(f"  v={v:>3} m/s: DAF={res.daf:.3f}, peak={np.max(np.abs(res.w_mid))*1e3:.2f} mm, "
              f"B-WIM {Wr/1e3:.1f} kN")

    mag = (0.12 * L) / max_w if max_w > 0 else 1.0
    data = {
        "meta": {"L": L, "n_nodes": beam.n_nodes, "mag": mag, "weight": W,
                 "static_midspan": static_mid, "f1": f1, "damping_pct": ZETA * 100,
                 "gauge_x": X_GAUGE, "n_speeds": len(SPEEDS)},
        "node_x": node_x, "speeds": SPEEDS,
        "daf_curve": [s["daf"] for s in scenarios],
        "scenarios": scenarios,
    }

    def enc(o):
        if isinstance(o, np.ndarray): return [round(float(v), 7) for v in o]
        if isinstance(o, (np.floating, float)): return round(float(o), 7)
        if isinstance(o, (np.integer, int)): return int(o)
        if isinstance(o, dict): return {k: enc(v) for k, v in o.items()}
        if isinstance(o, list): return [enc(v) for v in o]
        return o

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, "output"); os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "explore_data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// generated by solver/export_explore.py\n")
        fh.write("const EXPLORE_DATA = " + json.dumps(enc(data)) + ";\n")
    print(f"\nwrote {out}  ({os.path.getsize(out)/1024:.0f} kB, mag x{mag:.0f}, "
          f"f1={f1:.2f} Hz)")


if __name__ == "__main__":
    main()
