"""Export the KW51 'bridge heartbeat' series for the BridgeBeat web demo.

Takes the real 16-month tracked modal frequency of the KW51 bridge (mode 5, the
best-tracked one with a clear retrofit jump), bins it to a clean daily median so it
reads as a smooth pulse line, and writes it as injected JS for the web page.

    python -u solver/export_bridgebeat.py   ->  output/bridgebeat_data.js

This is REAL measured data (Zenodo 3745914). The web page animates it like a heart
monitor; the retrofit day is where the pulse visibly steps up. numpy core; scipy.io
to load the .mat (tooling).
"""

import json
import os
from datetime import datetime, timedelta

import numpy as np

MODE = 5                                      # 2.94 Hz, 96.5% tracked, +2.1% jump
RETROFIT_START = datetime(2019, 5, 15)
RETROFIT_END = datetime(2019, 9, 27)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAT = os.path.join(ROOT, "data", "trackedmodes", "trackedmodes.mat")


def datenum_to_dt(x):
    return datetime.fromordinal(int(x) - 366) + timedelta(days=float(x) % 1)


def main():
    if not os.path.exists(MAT):
        print(f"[!] {MAT} not found. Fetch KW51 first (see verify_kw51.py docstring).")
        return
    import scipy.io
    m = scipy.io.loadmat(MAT, squeeze_me=True, struct_as_record=False)["modes"]
    sdn = np.asarray(m.sdn, float)
    f = np.asarray(m.f, float)[:, MODE]
    T = np.asarray(m.env, float)[:, 0]            # bridge-deck temperature

    # daily median bins -> a clean, continuous pulse line
    day = np.floor(sdn).astype(int)
    days = np.unique(day)
    dates, fday, Tday = [], [], []
    for d in days:
        sel = day == d
        fv = f[sel]
        if np.all(np.isnan(fv)):
            continue
        dates.append(datenum_to_dt(d))
        fday.append(float(np.nanmedian(fv)))
        Tday.append(float(np.nanmedian(T[sel])))
    dates = np.array(dates); fday = np.array(fday); Tday = np.array(Tday)

    before = dates < RETROFIT_START
    after = dates > RETROFIT_END
    f_before = float(np.nanmean(fday[before]))
    f_after = float(np.nanmean(fday[after]))
    jump_pct = 100 * (f_after - f_before) / f_before

    data = {
        "meta": {
            "bridge": "KW51 (Leuven, Belgium) - real monitoring data",
            "source": "Maes & Lombaert, Zenodo 3745914",
            "mode": int(MODE),
            "f_mean_hz": round(float(np.nanmean(fday)), 4),
            "span": [dates[0].strftime("%Y-%m-%d"), dates[-1].strftime("%Y-%m-%d")],
            "retrofit": [RETROFIT_START.strftime("%Y-%m-%d"),
                         RETROFIT_END.strftime("%Y-%m-%d")],
            "f_before_hz": round(f_before, 4),
            "f_after_hz": round(f_after, 4),
            "jump_pct": round(jump_pct, 2),
            "n_days": int(len(dates)),
            "T_min": round(float(np.nanmin(Tday)), 1),
            "T_max": round(float(np.nanmax(Tday)), 1),
        },
        "date": [d.strftime("%Y-%m-%d") for d in dates],
        "f": [round(v, 4) for v in fday],
        "T": [round(v, 1) for v in Tday],
    }

    out = os.path.join(ROOT, "output", "bridgebeat_data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// generated by solver/export_bridgebeat.py - REAL KW51 data\n")
        fh.write("const BRIDGEBEAT = " + json.dumps(data) + ";\n")

    print(f"KW51 heartbeat: mode {MODE}, {len(dates)} daily points "
          f"{data['meta']['span'][0]} -> {data['meta']['span'][1]}")
    print(f"  f before retrofit = {f_before:.3f} Hz, after = {f_after:.3f} Hz "
          f"({jump_pct:+.1f}%)")
    print(f"  deck T range {data['meta']['T_min']}..{data['meta']['T_max']} degC")
    print(f"wrote {out}  ({os.path.getsize(out)/1024:.0f} kB)")


if __name__ == "__main__":
    main()
